### ISSUE TITLE
Add HubSpot Contacts integration

### ISSUE THREAD

**Issue by grokify** [zxdong262/hubspot-embeddable-ringcentral-phone#28]
Add custom contacts integration the using HubSpot contacts API per the section "Contacts Integration" in the blog article below:

https://medium.com/ringcentral-developers/custom-extensions-for-the-ringcentral-embeddable-voice-web-widget-f7730ea882b1

This way when an incoming call comes in, the user's HubSpot name will show up in the inbound call screen.

![](https://cdn-images-1.medium.com/max/1200/1*Vh-pO7RY1j0PTeeROpHvTw.png)

**Comment by zxdong262** [comment]
Already done, should be this problem: https://github.com/zxdong262/hubspot-embeddable-ringcentral-phone/issues/29
