### ISSUE TITLE
trouble with npm start step

### ISSUE THREAD

**Issue by bjsvec** [zxdong262/hubspot-embeddable-ringcentral-phone#76]
I am a wannabe dev so bear with me.  I really want to try to get this to work and installed Xcode, brew, npm and node and followed the instructions.  I get stuck after running _npm start_ and get the following warning.  I am not able to go to the next step of adding the unpacked extension into Chrome.

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  content.js (365 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  content (365 KiB)
      content.js

WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

**Comment by zxdong262** [comment]
This warning would not stop building process, in `dist`, is there a  `content.js` created?
If so, just continue the steps.
If not, I may need more info, maybe you could add a screenshot?

**Comment by bjsvec** [comment]
I just discovered my error.  Somehow I created two similar, but different directories while trying to figure this all out.

![screen shot 2018-10-02 at 5 40 50 pm](https://user-images.githubusercontent.com/43792275/46384384-71a0d980-c66a-11e8-99d4-1dfd00805c3c.png)

Not sure how I managed that, but I did get this working now.  Thank you.
