### ISSUE TITLE
Mobile/other phone number check

### ISSUE THREAD

**Issue by zxdong262** [zxdong262/hubspot-embeddable-ringcentral-phone#79]
https://devcommunity.ringcentral.com/ringcentraldev/topics/hubspot-api-integration

**Comment by zxdong262** [comment]
I know their csrf token now, and I know their api to get all phonenumbers, but it is not very practical: To fetch the contact list, I have to send req for every contact. That is not right.

**Comment by bjsvec** [comment]
That's too bad.  I am evaluating your last release 0.0.23 now and it seems to not want to sync my Hubspot contacts after authorization.  I see the Hubspot dropdown in the RC widget, but no contacts.  I had seen them before on a previous version, but have had to unauthorized and reauthorize and refresh or close/open browser a few times.

**Comment by bjsvec** [comment]
I also wonder if it is really necessary to sync to the entire contact list.  Since the way I imagine the would typically be used is within Hubspot that already acts as the main phone directory maybe it is only necessary to do a sync/lookup per each outbound or inbound call?

**Comment by zxdong262** [comment]
> Hubspot api just do not supply the mobile phone number, not sure why, anyway I already post a question in hubspot dev forum. https://integrate.hubspot.com/t/property-mobilephone-not-working/13124/2

My mistake, their api do have the mobile phone data

**Comment by zxdong262** [comment]
> That's too bad. I am evaluating your last release 0.0.23 now and it seems to not want to sync my Hubspot contacts after authorization. I see the Hubspot dropdown in the RC widget, but no contacts. I had seen them before on a previous version, but have had to unauthorized and reauthorize and refresh or close/open browser a few times.
@bjsvec 
0.0.23 do sync mobile phone, and the auth problem, not happened in my browser, maybe there is some bug I did not find yet. I will try to find it.

**Comment by bjsvec** [comment]
I'm running MacOS 10.14 and Chrome 69.0.3497.100 (Official Build) (64-bit) for reference.  Let me know if I can help in any way.  I will find the right thread to post some screenshots about it.
